---
title       : Gompertz Function
subtitle    : Modelling Constrained Growth
author      : Brandon Bartell
job         : Nerd
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
url:
#  lib: ../../libraries
  lib: ../../librariesNew
  assets: ../../assets
widgets     : [mathjax, quiz, bootstrap]
mode        : selfcontained
---

## What is the Gompertz function?

- The Gompertz function is a simple mathematical model for constrained growth as a function of time.

- It was named after [Benjamin Gompertz](http://en.wikipedia.org/wiki/Benjamin_Gompertz), who was a british mathematician and actuary.

- It takes the form:
  $$latex y(t)=a e^{-b e^{-c t}} $$

- a, b, and c are the three parameters that describe the shape as the function varies with time, t

---

## Why use it?

- The Gompertz function is practical for its simplicity and power
- With 3 simple parameters, you can easily model 
  - Population growth with finite resources
  - Tumor growth in a confined space
  - Product/technology share uptake to peak share

---

## What does each parameter do?

- Here are some examples showing how the curve moves with each parameter, leaving the other parameters fixed.


```{r echo=FALSE}
gompertz<-function(a,b,c,t) a*exp(-b*exp(-c*t))
t<-seq(-4,4,length.out=80)
a<-c(1,2,3); b<-c(1,2,3);c<-c(1,2,3)
test<-c(2,3)
par(mfrow=c(1,3),mar=c(5.1,4.1,4.1,4.1),oma=c(0,0,0,0))
plot(t,gompertz(a[1],b[1],c[1],t),type="l",xlab="t",ylab="y",main="Varying a", ylim=c(0,3))
for(i in 2:3) lines(t,gompertz(a[i],b[1],c[1],t),col=i)
plot(t,gompertz(a[1],b[1],c[1],t),type="l",xlab="t",ylab="y",main="Varying b")
for(i in 2:3) lines(t,gompertz(a[1],b[i],c[1],t),col=i)
plot(t,gompertz(a[1],b[1],c[1],t),type="l",xlab="t",ylab="y",main="Varying c")
for(i in 2:3) lines(t,gompertz(a[1],b[1],c[i],t),col=i)
```

---

## Playing with it yourself!

- In order to understand what each parameter in the Gompertz function does, it is useful to play with each parameter and visually see it's effect on the shape of the curve.

- [My shiny app](https://bartellbl.shinyapps.io/myApp2/) lets the user change the three parameters and the plotting range interactively.

- Try it for yourself!


---
